version: '3'

services:
  redis:
    image: 'bitnami/redis:5.0.9'
    container_name: 'redis'
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=1234
    user: root
    volumes:
      - './redis:/bitnami/redis/data'
